INSERT INTO jobs (name, type, description)
VALUES
    ('Software Engineer', 'Full-time', 'Develop and maintain software applications'),
    ('Marketing Manager', 'Full-time', 'Develop marketing strategies and campaigns'),
    ('Graphic Designer', 'Part-time', 'Create visually appealing designs for various projects'),
    ('Sales Representative', 'Full-time', 'Promote and sell products to customers'),
    ('Data Analyst', 'Contract', 'Analyze and interpret data for business insights'),
    ('Web Developer', 'Full-time', 'Design and develop web applications'),
    ('Accountant', 'Full-time', 'Manage financial records and perform audits'),
    ('Customer Service Representative', 'Part-time', 'Assist customers with inquiries and provide support'),
    ('Project Manager', 'Full-time', 'Plan and oversee project execution'),
    ('Content Writer', 'Contract', 'Create engaging and informative content'),
    ('Software Tester', 'Full-time', 'Perform testing and quality assurance on software'),
    ('Human Resources Specialist', 'Full-time', 'Manage employee relations and HR processes'),
    ('Data Scientist', 'Full-time', 'Analyze complex data sets and build predictive models'),
    ('Sales Manager', 'Full-time', 'Lead and motivate sales team to achieve targets'),
    ('UX/UI Designer', 'Contract', 'Design intuitive user interfaces and experiences'),
    ('Operations Coordinator', 'Full-time', 'Coordinate operational activities and ensure efficiency'),
    ('Financial Analyst', 'Full-time', 'Analyze financial data and provide insights'),
    ('Product Manager', 'Full-time', 'Manage product lifecycle and roadmap'),
    ('IT Support Specialist', 'Part-time', 'Provide technical assistance to users'),
    ('Marketing Coordinator', 'Full-time', 'Assist in planning and executing marketing campaigns'),
    ('Research Scientist', 'Full-time', 'Conduct scientific research and experiments'),
    ('Administrative Assistant', 'Part-time', 'Provide administrative support to the team'),
    ('Network Engineer', 'Full-time', 'Design and maintain network infrastructure'),
    ('Social Media Manager', 'Full-time', 'Manage social media accounts and campaigns'),
    ('Business Analyst', 'Full-time', 'Gather and analyze business requirements'),
    ('Event Planner', 'Contract', 'Organize and coordinate events and conferences'),
    ('Operations Manager', 'Full-time', 'Oversee day-to-day operations and optimize processes'),
    ('Frontend Developer', 'Full-time', 'Build user interfaces for web applications'),
    ('Data Engineer', 'Full-time', 'Design and implement data pipelines'),
    ('Sales Associate', 'Part-time', 'Assist customers with purchases and inquiries'),
    ('Quality Assurance Analyst', 'Full-time', 'Test software applications for bugs and issues'),
    ('Business Development Manager', 'Full-time', 'Identify and pursue business growth opportunities'),
    ('UI/UX Designer', 'Contract', 'Create visually appealing and user-friendly designs'),
    ('Supply Chain Analyst', 'Full-time', 'Analyze and optimize supply chain processes'),
    ('Digital Marketing Specialist', 'Full-time', 'Develop and implement digital marketing strategies'),
    ('Research Assistant', 'Part-time', 'Support research projects and data collection'),
    ('Systems Administrator', 'Full-time', 'Manage and maintain computer systems and servers'),
    ('Content Marketing Manager', 'Full-time', 'Plan and execute content marketing campaigns'),
    ('Data Entry Clerk', 'Part-time', 'Enter and manage data in databases and systems'),
    ('UX Researcher', 'Full-time', 'Conduct user research and usability testing'),
    ('Financial Controller', 'Full-time', 'Oversee financial operations and reporting'),
    ('IT Project Manager', 'Full-time', 'Manage and deliver IT projects on time and within budget'),
    ('Social Media Specialist', 'Full-time', 'Manage social media accounts and engage with followers'),
    ('Business Consultant', 'Full-time', 'Provide expert advice and solutions to clients'),
    ('Event Coordinator', 'Contract', 'Plan and coordinate events and conferences'),
    ('Operations Analyst', 'Full-time', 'Analyze operational data and identify improvements'),
    ('Legal Assistant', 'Full-time', 'Provide administrative support to legal professionals');

INSERT INTO person_job (person_id, job_id)
VALUES
    (1, 5),
    (2, 12),
    (3, 10),
    (4, 18),
    (5, 7),
    (6, 13),
    (7, 20),
    (8, 3),
    (9, 9),
    (10, 15),
    (11, 18),
    (12, 25),
    (13, 6),
    (14, 14),
    (15, 21),
    (16, 13),
    (17, 19),
    (18, 24),
    (19, 26),
    (20, 17),
    (21, 23),
    (22, 28),
    (23, 1),
    (24, 10),
    (25, 16),
    (1, 11),
    (2, 22),
    (3, 4),
    (4, 7),
    (5, 15),
    (6, 26),
    (7, 28),
    (8, 16),
    (9, 23),
    (10, 27),
    (11, 1),
    (12, 8),
    (13, 19),
    (14, 27),
    (15, 15),
    (16, 21),
    (17, 24),
    (19, 28),
    (20, 22),
    (21, 27),
    (22, 2),
    (23, 14),
    (24, 21),
    (25, 25),
    (1, 10),
    (1, 25),
    (2, 5),
    (2, 20),
    (3, 15),
    (3, 30),
    (4, 12),
    (4, 27),
    (5, 18),
    (5, 40),
    (6, 22),
    (6, 35),
    (7, 8),
    (7, 17),
    (8, 13),
    (8, 32),
    (9, 28),
    (9, 45),
    (10, 4),
    (10, 42),
    (11, 23),
    (11, 37),
    (12, 7),
    (12, 16),
    (13, 30),
    (13, 47),
    (14, 10),
    (14, 21),
    (15, 33),
    (15, 40),
    (16, 2),
    (16, 15),
    (17, 18),
    (17, 35),
    (18, 5),
    (18, 25),
    (19, 14),
    (19, 31),
    (20, 27),
    (20, 45),
    (21, 20),
    (21, 42),
    (22, 8),
    (22, 17),
    (23, 11),
    (23, 28),
    (24, 22),
    (24, 37),
    (25, 3);